# Generated by Django 4.1 on 2022-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('brief', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('blogImage', models.ImageField(default='', upload_to='blogImage/')),
                ('visibility', models.BooleanField(default=False)),
                ('pub_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(default='', upload_to='profile/')),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('instaProfile', models.URLField(max_length=500)),
                ('twitterProfile', models.URLField(max_length=500)),
                ('fbProfile', models.URLField(max_length=500)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
