# Generated by Django 4.1 on 2022-08-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='fbProfile',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='instaProfile',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='twitterProfile',
        ),
    ]
